# Ingress Configuration.
ingress:
  # The name of the cluster issuers for ingress. By default is set to letsencrypt with http01 challenge.
  # Default: "letsencrypt-http-prod"
  clusterIssuers: "letsencrypt-http-prod"

# Number of replicas of this Shibboleth IdP.
# Default: 1
replicaCount: 1

# Container images used for the Shibboleth IdP.
image:
  # Shibboleth IdP.
  shibboleth:
    # Shibboleth IdP image registry.
    # Default: "ghcr.io"
    registry: "ghcr.io"
    # Shibboleth IdP image repository.
    # Default: "sifulan-access-federation/ifirexman-shibboleth-idp-base"
    repository: "sifulan-access-federation/ifirexman-shibboleth-idp-base"
    # Shibboleth IdP image version.
    # Default: Chart appVersion
    tag: ""
    # Shibboleth IdP image pull policy.
    # Default: "IfNotPresent"
    pullPolicy: "IfNotPresent"

  # HTTPD.
  httpd:
    # HTTPD image registry.
    # Default: "ghcr.io"
    registry: "ghcr.io"
    # HTTPD image repository.
    # Default: "sifulan-access-federation/shibboleth-idp-httpd"
    repository: "sifulan-access-federation/shibboleth-idp-httpd"
    # HTTPD image version.
    # Default: "master"
    tag: ""
    # HTTPD image pull policy.
    # Default: "IfNotPresent"
    pullPolicy: "IfNotPresent"

# Set the minimum and maximum number of memory and cpu for the containers.
resources:
  # Shibboleth IdP resources.
  shibboleth:
    requests:
      # Minimum CPU allocation.
      # Example:
      # cpu: "10m"
      cpu: "0.1"
      # Minimum memory allocation.
      # Example:
      # memory: "10Mi"
      memory: "1Gi"
    limits:
      # Maximum CPU allocation.
      # Example:
      # cpu: "2"
      cpu: "0.5"
      # Maximum memory allocation.
      # Example:
      # memory: "2Gi"
      memory: "2Gi"
  # HTTPD resources.
  httpd:
    requests:
      # Minimum CPU allocation.
      # Example:
      # cpu: "10m"
      cpu: "0.1"
      # Minimum memory allocation.
      # Example:
      # memory: "10Mi"
      memory: "1Gi"
    limits:
      # Maximum CPU allocation.
      # Example:
      # cpu: "2"
      cpu: "0.5"
      # Maximum memory allocation.
      # Example:
      # memory: "2Gi"
      memory: "2Gi"

# IdP Configuration
idp:
  # The sub-domain name of the IdP.
  # Example:
  # domain: "idp.ifirexman.edu"
  domain: ""
  # The scope name of the IdP. Typically set to the domain name.
  # Example:
  # scope: "ifirexman.edu"
  scope: ""
  # The full name of the organisation where this IdP belongs to.
  # Example:
  # fullname: "iFIRExMAN Virtual Organisation"
  fullname: ""
  # The short name/acronym of the organisation where this IdP belongs to.
  # Example:
  # shortname: "iFIRExMAN"
  shortname: ""
  # Brief description of the organisation where this IdP belongs to.
  # Example:
  # description: "Research and Education Communities"
  description: "Research and Education Communities"
  # The website url of the organisation where this IdP belongs to.
  # Example:
  # website: "https://ifirexman.edu"
  website: ""
  # The country code (in lower letter) of the organisation where this IdP belongs to.
  # Example:
  # country: "my"
  country: ""
  # The support email address of the organisation where this IdP belongs to. Should be a role-based email instead of a personal email.
  # Example:
  # support_email: "support@ifirexman.edu"
  support_email: ""
  # The password reset url of the organisation where this IdP belongs to.
  # Default: "#"
  # Example:
  # password_reset_url: "https://ifirexman.edu/password-reset"
  password_reset_url: ""
  # Attribute Release Policy
  # Example:
  # attribute_release_policy:
  # - name: "releaseEpSA"
  #   entity_id:
  #     - https://sp1.ifirexman.edu/shibboleth
  #     - https://sp2.ifirexman.edu/shibboleth
  #   attributes:
  #     - eduPersonScopedAffiliation
  #     - eduPersonEntitlement
  #     - eduPersonTargetedID
  attribute_release_policies: []
  # Log Persistence Configuration.
  persistent_log:
    # Enable log persistence.
    enabled: false
    # Set the storage class to use for the persistent log.
    # Example:
    # storage_class: "longhorn"
    storage_class: "longhorn"
    # Set the maximum size of the persistent log.
    # Example:
    # size: "1Gi"
    size: "1Gi"
  # Fticks Configuration.
  fticks:
    # Enable fticks support.
    # Example:
    # enabled: false
    enabled: false
  # VIKINGS Specific Configuration
  vikings:
    # Set to true if this IdP uses VIKINGS as the backend authenticator.
    # Example:
    # enabled: true
    enabled: false
    # Set VIKINGS's database server host.
    # Example:
    # database_hostname: "mariadb.central-svcs.svc.cluster.local"
    database_hostname: ""
    # Set VIKINGS's database name.
    # Example:
    # database_name: "vikings"
    database_name: ""
    # Set VIKINGS's database username.
    # Example:
    # database_username: "vikings"
    database_username: ""
    # Set VIKINGS's database password.
    # Example:
    # database_password: "vikings"
    database_password: ""
  # Azure AD Specific Configuration.
  azure_ad:
    # Set to true if this IdP uses Azure AD as the backend authenticator.
    # Example:
    # enabled: true
    enabled: false
    # Set Azure AD's entity_id.
    # Example:
    # entity_id: "https://sts.windows.net/9f8177eb-5934-427f-9748-f38e86a0a475/"
    entity_id: ""
    # Azure AD eduPersonAffiliation Attribute Mapping.
    # Example:
    # eduPersonAffiliationAttributeMap:
    #   attribute: "mail"
    #   valueMap:
    #     - attributeReturn: "staff"
    #       attributeValues:
    #         - "@ifirexman.edu"
    #     - attributeReturn: "student"
    #       attributeValues:
    #         - "@student.ifirexman.edu"
    #     - attributeReturn: "member"
    #       attributeValues:
    #         - "@ifirexman.edu"
    #         - "@student.ifirexman.edu"
    eduPersonAffiliationAttributeMap:
      attribute: ""
      valueMap: []
    # Azure AD eduPersonEntitlement Attribute Mapping.
    # Example:
    # eduPersonEntitlementAttributeMap:
    #   attribute: "eduPersonAffiliation"
    #   valueMap:
    #     - attributeReturn: "urn:mace:ifirexman.edu:staff"
    #       attributeValues:
    #         - "staff"
    #     - attributeReturn: "urn:mace:ifirexman.edu:student"
    #       attributeValues:
    #         - "student"
    #     - attributeReturn: "urn:mace:ifirexman.edu:member"
    #       attributeValues:
    #         - "member"
    #     - attributeReturn: "urn:mace:dir:entitlement:common-lib-terms"
    #       attributeValues:
    #         - "member"
    eduPersonEntitlementAttributeMap:
      attribute: ""
      valueMap: []
    # Azure AD IdP metadata file.
    metadata: ""
  # Google Workspace Specific Configuration.
  google:
    # Set to true if this IdP uses Google Workspace as the backend authenticator.
    # Example:
    # enabled: true
    enabled: false
    # Set Google Workspace's entity_id.
    # Example:
    # entity_id: "https://accounts.google.com/o/saml2?idpid=LqF825zMf"
    entity_id: ""
    # Google eduPersonAffiliation Attribute Mapping.
    # Example:
    # eduPersonAffiliationAttributeMap:
    #   attribute: "mail"
    #   valueMap:
    #     - attributeReturn: "staff"
    #       attributeValues:
    #         - "@ifirexman.edu"
    #     - attributeReturn: "student"
    #       attributeValues:
    #         - "@student.ifirexman.edu"
    #     - attributeReturn: "member"
    #       attributeValues:
    #         - "@ifirexman.edu"
    #         - "@student.ifirexman.edu"
    eduPersonAffiliationAttributeMap:
      attribute: ""
      valueMap: []
    # Google eduPersonEntitlement Attribute Mapping.
    # Example:
    # eduPersonEntitlementAttributeMap:
    #   attribute: "eduPersonAffiliation"
    #   valueMap:
    #     - attributeReturn: "urn:mace:ifirexman.edu:staff"
    #       attributeValues:
    #         - "staff"
    #     - attributeReturn: "urn:mace:ifirexman.edu:student"
    #       attributeValues:
    #         - "student"
    #     - attributeReturn: "urn:mace:ifirexman.edu:member"
    #       attributeValues:
    #         - "member"
    #     - attributeReturn: "urn:mace:dir:entitlement:common-lib-terms"
    #       attributeValues:
    #         - "member"
    eduPersonEntitlementAttributeMap:
      attribute: ""
      valueMap: []
    # Google Workspace IdP metadata file.
    metadata: ""
  # IdP Signing Certificate file.
  signing_cert: ""
  # IdP Signing Key file.
  signing_key: ""
  # IdP Encryption Certificate file.
  encryption_cert: ""
  # IdP Encryption Key file.
  encryption_key: ""
  # IdP Sealer JKS file.
  sealer_jks: ""
  # IdP Sealer kver file.
  sealer_kver: ""
  # IdP secrets.properties file.
  secrets_properties: ""

# Federation Configuration.
federation:
  # Federation Full Name.
  # Example:
  # fullname: "iFIRExMAN Federation"
  fullname: ""
  # Federation Short Name/Acronym.
  # Example:
  # shortname: "iFIRExMAN"
  shortname: ""
  # Federation Registration Authority.
  # Example:
  # registration_authority: "https://ifirexman.edu"
  registration_authority: ""
  # Federation MDQ Server URL.
  # Example:
  # mdq_url: "https://mdq.ifirexman.edu"
  mdq_url: ""
  # Federation Support Email.
  # Example:
  # support_email: "support@ifirexman.edu"
  support_email: ""
  # Federation Syslog Server.
  # Example:
  # syslog_server: "syslog.ifirexman.edu"
  syslog_server: ""
  # Federation Signer Certificate file.
  signer_cert: ""
