# Default values for ssotest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Number of replicas of SSO Test
# Default: 1
replicaCount: 1

# Container image
image:
  # SSO Test
  ssotest:
    # SSO Test image registry
    # Default: "ghcr.io"
    registry: "ghcr.io"
    # SSO Test image repository
    # Default: "sifulan-access-federation/ifirexman-ssotest"
    repository: "sifulan-access-federation/ifirexman-ssotest"
    # SSO Test image version
    # Default: Chart appVersion
    tag: ""
    # SSO Test image pull policy
    # Default: "IfNotPresent"
    pullPolicy: "IfNotPresent"

# Ingress configuration
ingress:
  # Ingress cluster issuer
  # Default: "letsencrypt-http-prod"
  clusterIssuers: "letsencrypt-http-prod"

# Container resources
resources:
  # SSO Test
  ssotest:
    requests:
      # Minimum CPU allocation
      # Example:
      # cpu: "10m"
      cpu: "0.5"
      # Minimum memory allocation
      # Example:
      # memory: "10Mi"
      memory: "0.5Gi"
    limits:
      # Maximum CPU allocation
      # Example:
      # cpu: "2"
      cpu: "1"
      # Maximum memory allocation
      # Example:
      # memory: "2Gi"
      memory: "1Gi"

# SSO Test configuration
ssotest:
  # Portal hostname
  # Example:
  # hostname: "ssotest.ifirexman.edu"
  hostname: ""
  # Shibboleth SP Entity ID
  # Example:
  # entity_id: "https://ssotest.ifirexman.edu/shibboleth"
  entity_id: ""
  # Support email address
  # Example:
  # support: "support@ifirexman.edu"
  support: ""
  # Shibboleth SP signing certificate
  # Refer to README on how to generate signing.crt file
  signing_crt: ""
  # Shibboleth SP signing key
  # Refer to README on how to generate signing.key file
  signing_key: ""
  # Shibboleth SP encryption certificate
  # Refer to README on how to generate encrypt.crt file
  encryption_crt: ""
  # Shibboleth SP encryption key
  # Refer to README on how to generate encrypt.key file
  encryption_key: ""
  # Optional: shibboleth2.xml file
  sp_config: ""
  # Optional: attribute-map.xml file
  attribute_map: ""

# Federation configuration
federation:
  # Federation full name
  # Example:
  # fullname: "iFIRExMAN Federation"
  name: ""
  # Federation support email address
  # Example:
  # support_email: "support@ifirexman.edu"
  support: ""
  # MDQ Server URL
  # Example:
  # mdq_url: "https://mdq.ifirexman.edu/"
  mdq_url: ""
  # WAYF Server URL
  # Example:
  # wayf_url: "https://ds.ifirexman.edu/ds/WAYF"
  wayf_url: ""
  # Federation signing certificate
  # Refer to README on how to get fed-signer.crt file
  signer: ""
